create index if not exists idx_org_units_organization_id on org_units (organization_id);
create index if not exists idx_users_organization_id on users (organization_id);
create index if not exists idx_user_roles_role_id on user_roles (role_id);
create index if not exists idx_clients_organization_id on clients (organization_id);
create index if not exists idx_projects_client_id on projects (client_id);
create index if not exists idx_projects_organization_id on projects (organization_id);
create index if not exists idx_sites_project_id on sites (project_id);
create index if not exists idx_work_categories_organization_id on work_categories (organization_id);
create index if not exists idx_attendance_policies_organization_id on attendance_policies (organization_id);
create index if not exists idx_attendance_logs_org_user_time on attendance_logs (organization_id, user_id, occurred_at desc);
create index if not exists idx_attendance_logs_work_session_id on attendance_logs (work_session_id);
create index if not exists idx_work_sessions_org_date on work_sessions (organization_id, session_date desc);
create index if not exists idx_work_sessions_org_user_status on work_sessions (organization_id, user_id, status);
create index if not exists idx_work_session_logs_session_id on work_session_logs (work_session_id, created_at desc);
create index if not exists idx_work_entries_session_id on work_entries (work_session_id);
create index if not exists idx_daily_reports_org_user_date on daily_reports (organization_id, user_id, report_date desc);
create index if not exists idx_approval_requests_target on approval_requests (target_type, target_id);
create index if not exists idx_closing_periods_org_dates on closing_periods (organization_id, period_start, period_end);
create index if not exists idx_files_organization_id on files (organization_id);
create index if not exists idx_external_mappings_entity on external_mappings (entity_type, entity_id);
create index if not exists idx_export_batches_organization_id on export_batches (organization_id, status);
create index if not exists idx_outbox_events_unpublished on outbox_events (published_at) where published_at is null;
create index if not exists idx_audit_logs_org_created_at on audit_logs (organization_id, created_at desc);
create index if not exists idx_custom_field_definitions_org_entity on custom_field_definitions (organization_id, entity_type);
create index if not exists idx_custom_field_values_entity on custom_field_values (entity_id);
